name: Nix

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  develop:
    runs-on: ubuntu-24.04
    if: contains(github.event.head_commit.message, '构建app')
    steps:
      - name: Fetch source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: fcitx5-android
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Release APK
        env:
          SIGN_KEY_BASE64: ${{ secrets.SIGN_KEY_BASE64 }}
          SIGN_KEY_PWD: ${{ secrets.SIGN_KEY_PWD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        run: |
          nix develop .#noAS --command ./gradlew clean
          nix develop .#noAS --command ./gradlew :app:assembleRelease --stacktrace --info 2>&1 | tee build.log
          nix develop .#noAS --command ./gradlew :assembleReleasePlugins --stacktrace --info 2>&1 | tee -a build.log
      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: build-log
          path: build.log
      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: fcitx5-android-release
          path: app/build/outputs/apk/release/*.apk